name: ai-engineer-p14
services:
  p14-train:
    build:
      context: .
      dockerfile: docker/train/Dockerfile
    container_name: p14-train
    working_dir: /app
    volumes:
      - ./:/app
      - hf_cache:/root/.cache/huggingface
    environment:
      HF_HOME: /root/.cache/huggingface
      WANDB_API_KEY: ${WANDB_API_KEY}
      WANDB_PROJECT: ${WANDB_PROJECT:-chsa-finetuning}
      MODEL_NAME: ${MODEL_NAME}
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: bash

networks:
  p14_network:
    driver: bridge

volumes:
  hf_cache:

