name: ai-engineer-p13
services:
  p13-api:
    container_name: p13-api
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - DATA_DIR=.data
      - MILVUS_HOST=p13-milvus
      - MILVUS_PORT=19530
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - MILVUS_COLLECTION=${MILVUS_COLLECTION}
    command: poetry run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - p13-milvus
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - p13_network

  p13-client:
    container_name: p13-client
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3200:3200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0 --port 3200

  p13-etcd:
    container_name: p13-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: >
      etcd
      --advertise-client-urls=http://0.0.0.0:2379
      --listen-client-urls=http://0.0.0.0:2379
      --data-dir=/etcd
    volumes:
      - ./.data/etcd:/etcd
    networks:
      - p13_network

  p13-minio:
    container_name: p13-minio
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: minio server /minio_data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/minio_data
    networks:
      - p13_network

  p13-milvus:
    container_name: p13-milvus
    image: milvusdb/milvus:v2.3.9
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=p13-etcd:2379
      - MINIO_ADDRESS=p13-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - LOG_LEVEL=info
      - MILVUS_COLLECTION=${MILVUS_COLLECTION}
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./.data/milvus:/var/lib/milvus
    depends_on:
      - p13-etcd
      - p13-minio
    restart: unless-stopped
    networks:
      - p13_network

networks:
  p13_network:
    driver: bridge