name: ai-engineer-p7
services:
  api:
    container_name: p7-api
    build: .
    volumes:
      - ./:/app
    ports:
      - '${API_PORT}:80'
    environment:
      PYTHONPATH: /app
      API_URL: 'http://127.0.0.1:80'
      API_TOKEN: ${API_TOKEN}
      INDEX_DIR: ${INDEX_DIR}
      OPENDATASOFT_URL: ${OPENDATASOFT_URL}
      FILTER_YEARS: ${FILTER_YEARS}
      FILTER_DEPARTMENT: ${FILTER_DEPARTMENT}
      EMB_MODEL: ${EMB_MODEL}
      MISTRAL_TOKEN: ${MISTRAL_TOKEN}
      PROMPT_FILE: ${PROMPT_FILE}
    stdin_open: true
    tty: true
    networks:
      - ai-engineer-p7
  demo:
    container_name: p7-demo
    build: ./demo
    environment:
      API_URL: 'http://p7-api:80'
    ports:
      - '${DEMO_PORT}:7860'
    volumes:
      - ./demo:/app
    depends_on:
      - api
    networks:
      - ai-engineer-p7

networks:
  ai-engineer-p7:
    name: ai-engineer-p7
    driver: bridge