[tool.poetry]
name = "ai-engineer_p4"
version = "0.1.0"
description = "AI Engineer - Classifiez automatiquement des informations"
authors = ["Michaël Gonzalez <cyberalternative@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
jupyterlab = "^4.0.0"
pandas = "^2.3.2"
matplotlib = "^3.10.6"
seaborn = "^0.13.2"
scikit-learn = "^1.7.2"
xgboost = "^3.0.5"
shap = "^0.48.0"
imblearn = "^0.0"
joblib = "^1.5.2"
